# Generated by Django 5.0.6 on 2024-07-02 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_user_failed_login_attempts_user_last_login_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
