# Generated by Django 5.0.6 on 2024-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("market", models.CharField(max_length=50)),
                ("current_price", models.CharField(max_length=20)),
                ("previous_close", models.CharField(max_length=20)),
                ("day_range", models.CharField(max_length=50)),
                ("year_range", models.CharField(max_length=50)),
                ("market_cap", models.CharField(max_length=20)),
                ("avg_volume", models.CharField(max_length=20)),
                ("pe_ratio", models.CharField(max_length=10)),
                ("dividend_yield", models.CharField(max_length=10)),
                ("primary_exchange", models.CharField(max_length=50)),
            ],
        ),
    ]
