# Generated by Django 5.0.6 on 2024-07-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_time_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
